plugins { id 'com.android.application' }

android {
    namespace 'com.wladimir.nfccard'
    compileSdk 36

    defaultConfig {
        applicationId 'com.wladimir.nfccard'
        minSdk 29
        targetSdk 36
        versionCode 7
        versionName '7.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
